package com.cookandroid.app.model;

import android.content.Context;

import com.cookandroid.app.R;

import java.util.ArrayList;
import java.util.List;

public class FoodListProvider {
    private static List<FoodItem> data = null;

    public static List<FoodItem> getFoodList(Context context) {
        if (data == null) {
            data = new ArrayList<>();
            // 여기서 한 번만 객체 생성 (싱글톤 효과)
            // 기존 AddValueFragment에서 음식 생성하던 코드들 전부 여기로 옮김
            data.add(new FoodItem("가다랑어포", R.drawable.food1_1, "가공/유제품", "food1_1", 7));
            data.add(new FoodItem("계란", R.drawable.food1_2, "가공/유제품", "food1_2", 21));
            data.add(new FoodItem("다크초콜릿", R.drawable.food1_3, "가공/유제품", "food1_3", 154));
            data.add(new FoodItem("단무지", R.drawable.food1_4, "가공/유제품", "food1_4", 60));
            data.add(new FoodItem("두유", R.drawable.food1_5, "가공/유제품", "food1_5", 180));
            data.add(new FoodItem("라이스페이퍼", R.drawable.food1_6, "가공/유제품", "food1_6", 600));
            data.add(new FoodItem("만두", R.drawable.food1_7, "가공/유제품", "food1_7", 9));
            data.add(new FoodItem("만두피", R.drawable.food1_8, "가공/유제품", "food1_8", 15));
            data.add(new FoodItem("맛살", R.drawable.food1_9, "가공/유제품", "food1_9", 14));
            data.add(new FoodItem("모짜렐라치즈", R.drawable.food1_10, "가공/유제품", "food1_10", 14));
            data.add(new FoodItem("미트볼", R.drawable.food1_11, "가공/유제품", "food1_11", 7));
            data.add(new FoodItem("버터", R.drawable.food1_12, "가공/유제품", "food1_12", 45));
            data.add(new FoodItem("부라타치즈", R.drawable.food1_13, "가공/유제품", "food1_13", 7));
            data.add(new FoodItem("분유", R.drawable.food1_14, "가공/유제품", "food1_14", 30));
            data.add(new FoodItem("블랙올리브", R.drawable.food1_15, "가공/유제품", "food1_15", 14));
            data.add(new FoodItem("생크림", R.drawable.food1_16, "가공/유제품", "food1_16", 7));
            data.add(new FoodItem("아몬드우유", R.drawable.food1_17, "가공/유제품", "food1_17", 10));
            data.add(new FoodItem("연유", R.drawable.food1_18, "가공/유제품", "food1_18", 14));
            data.add(new FoodItem("요거트", R.drawable.food1_19, "가공/유제품", "food1_19", 14));
            data.add(new FoodItem("요구르트", R.drawable.food1_20, "가공/유제품", "food1_20", 30));
            data.add(new FoodItem("우유", R.drawable.food1_21, "가공/유제품", "food1_21", 22));
            data.add(new FoodItem("체다치즈", R.drawable.food1_22, "가공/유제품", "food1_22", 30));
            data.add(new FoodItem("초콜릿", R.drawable.food1_23, "가공/유제품", "food1_23", 120));
            data.add(new FoodItem("치즈", R.drawable.food1_24, "가공/유제품", "food1_24", 21));
            data.add(new FoodItem("크림치즈", R.drawable.food1_25, "가공/유제품", "food1_25", 14));
            data.add(new FoodItem("통조림옥수수", R.drawable.food1_26, "가공/유제품","food1_26", 7));
            data.add(new FoodItem("통조림참치", R.drawable.food1_27, "가공/유제품","food1_27", 7));
            data.add(new FoodItem("통조림햄", R.drawable.food1_28, "가공/유제품", "food1_28", 7));
            data.add(new FoodItem("파마산치즈", R.drawable.food1_29, "가공/유제품","food1_29", 60));
            data.add(new FoodItem("화이트초콜릿", R.drawable.food1_30, "가공/유제품", "food1_30", 120));
            data.add(new FoodItem("휘핑크림", R.drawable.food1_31, "가공/유제품", "food1_31", 7));

            data.add(new FoodItem("국거리소고기", R.drawable.food2_1, "고기", "food2_1", 4));
            data.add(new FoodItem("다진돼지고기", R.drawable.food2_2, "고기","food2_2", 2));
            data.add(new FoodItem("다진소고기", R.drawable.food2_3, "고기", "food2_3", 2));
            data.add(new FoodItem("닭가슴살", R.drawable.food2_4, "고기", "food2_4", 2));
            data.add(new FoodItem("닭고기", R.drawable.food2_5, "고기", "food2_5", 2));
            data.add(new FoodItem("닭날개", R.drawable.food2_6, "고기", "food2_6", 2));
            data.add(new FoodItem("닭다리", R.drawable.food2_7, "고기", "food2_7", 2));
            data.add(new FoodItem("대패삼겹살", R.drawable.food2_8, "고기", "food2_8", 4));
            data.add(new FoodItem("돼지 갈매기살", R.drawable.food2_9, "고기", "food2_9", 4));
            data.add(new FoodItem("돼지 뒷다리", R.drawable.food2_10, "고기", "food2_10", 4));
            data.add(new FoodItem("돼지 등심", R.drawable.food2_11, "고기", "food2_11", 4));
            data.add(new FoodItem("돼지 목살", R.drawable.food2_12, "고기", "food2_12", 4));
            data.add(new FoodItem("돼지 앞다리살", R.drawable.food2_13, "고기", "food2_13", 4));
            data.add(new FoodItem("돼지 항정살", R.drawable.food2_14, "고기", "food2_14", 4));
            data.add(new FoodItem("베이컨", R.drawable.food2_15, "고기", "food2_15", 7));
            data.add(new FoodItem("비엔나 소세지", R.drawable.food2_16, "고기", "food2_16", 7));
            data.add(new FoodItem("삼겹살", R.drawable.food2_17, "고기", "food2_17", 4));
            data.add(new FoodItem("소 등심", R.drawable.food2_18, "고기", "food2_18", 4));
            data.add(new FoodItem("소 안심", R.drawable.food2_19, "고기", "food2_19", 4));
            data.add(new FoodItem("소 채끝살", R.drawable.food2_20, "고기", "food2_20", 4));
            data.add(new FoodItem("소고기", R.drawable.food2_21, "고기", "food2_21", 4));
            data.add(new FoodItem("소고기 갈비", R.drawable.food2_22, "고기", "food2_22", 4));
            data.add(new FoodItem("소고기 목살", R.drawable.food2_23, "고기", "food2_23", 4));
            data.add(new FoodItem("소고기 사태", R.drawable.food2_24, "고기", "food2_24", 4));
            data.add(new FoodItem("소고기 앞다리살", R.drawable.food2_25, "고기", "food2_25", 4));
            data.add(new FoodItem("소고기 우둔", R.drawable.food2_26, "고기", "food2_26", 4));
            data.add(new FoodItem("소세지", R.drawable.food2_27, "고기", "food2_27", 53));
            data.add(new FoodItem("양고기", R.drawable.food2_28, "고기", "food2_28", 2));
            data.add(new FoodItem("잠봉", R.drawable.food2_29, "고기", "food2_28", 20));
            data.add(new FoodItem("차돌박이", R.drawable.food2_30, "고기", "food2_30", 4));
            data.add(new FoodItem("햄", R.drawable.food2_31, "고기", "food2_31", 50));
            data.add(new FoodItem("훈제오리", R.drawable.food2_32, "고기", "food2_32", 35));

            data.add(new FoodItem("감자전분", R.drawable.food3_1, "곡물", "food3_1", 180));
            data.add(new FoodItem("검은깨", R.drawable.food3_2, "곡물", "food3_2", 180));
            data.add(new FoodItem("귀리", R.drawable.food3_3, "곡물", "food3_3", 180));
            data.add(new FoodItem("깨", R.drawable.food3_4, "곡물", "food3_4", 180));
            data.add(new FoodItem("녹두", R.drawable.food3_5, "곡물", "food3_5", 180));
            data.add(new FoodItem("들깨가루", R.drawable.food3_6, "곡물", "food3_6", 90));
            data.add(new FoodItem("밀가루", R.drawable.food3_7, "곡물", "food3_7", 180));
            data.add(new FoodItem("밥", R.drawable.food3_8, "곡물", "food3_8", 3));
            data.add(new FoodItem("백미", R.drawable.food3_9, "곡물", "food3_9", 180));
            data.add(new FoodItem("보리", R.drawable.food3_10, "곡물", "food3_10", 180));
            data.add(new FoodItem("부침가루", R.drawable.food3_11, "곡물", "food3_11", 120));
            data.add(new FoodItem("빵가루", R.drawable.food3_12, "곡물", "food3_12", 90));
            data.add(new FoodItem("쌀가루", R.drawable.food3_13, "곡물", "food3_13", 90));
            data.add(new FoodItem("옥수수", R.drawable.food3_14, "곡물", "food3_14", 5));
            data.add(new FoodItem("전분", R.drawable.food3_15, "곡물", "food3_15", 180));
            data.add(new FoodItem("찹쌀", R.drawable.food3_16, "곡물", "food3_16", 180));
            data.add(new FoodItem("치아씨드", R.drawable.food3_17, "곡물", "food3_17", 365));
            data.add(new FoodItem("튀김가루", R.drawable.food3_18, "곡물", "food3_18", 120));
            data.add(new FoodItem("팥", R.drawable.food3_19, "곡물", "food3_19", 180));
            data.add(new FoodItem("현미", R.drawable.food3_20, "곡물", "food3_20", 120));
            data.add(new FoodItem("흑미", R.drawable.food3_21, "곡물", "food3_21", 120));

            data.add(new FoodItem("감", R.drawable.food4_1, "과일", "food4_1", 14));
            data.add(new FoodItem("곶감", R.drawable.food4_2, "과일", "food4_2", 30));
            data.add(new FoodItem("귤", R.drawable.food4_3, "과일", "food4_3", 14));
            data.add(new FoodItem("딸기", R.drawable.food4_4, "과일", "food4_4", 5));
            data.add(new FoodItem("레몬", R.drawable.food4_5, "과일", "food4_5", 21));
            data.add(new FoodItem("망고", R.drawable.food4_6, "과일", "food4_6", 7));
            data.add(new FoodItem("매실", R.drawable.food4_7, "과일", "food4_7", 14));
            data.add(new FoodItem("멜론", R.drawable.food4_8, "과일", "food4_8", 7));
            data.add(new FoodItem("바나나", R.drawable.food4_9, "과일", "food4_9", 7));
            data.add(new FoodItem("배", R.drawable.food4_10, "과일", "food4_10", 14));
            data.add(new FoodItem("복숭아", R.drawable.food4_11, "과일", "food4_11", 5));
            data.add(new FoodItem("블루베리", R.drawable.food4_12, "과일", "food4_12", 7));
            data.add(new FoodItem("사과", R.drawable.food4_13, "과일", "food4_13", 30));
            data.add(new FoodItem("샤인머스캣", R.drawable.food4_14, "과일", "food4_14", 10));
            data.add(new FoodItem("수박", R.drawable.food4_15, "과일", "food4_15", 7));
            data.add(new FoodItem("오렌지", R.drawable.food4_16, "과일", "food4_16", 21));
            data.add(new FoodItem("자두", R.drawable.food4_17, "과일", "food4_17", 7));
            data.add(new FoodItem("자몽", R.drawable.food4_18, "과일", "food4_18", 21));
            data.add(new FoodItem("키위", R.drawable.food4_19, "과일", "food4_19", 14));
            data.add(new FoodItem("파인애플", R.drawable.food4_20, "과일", "food4_20", 5));
            data.add(new FoodItem("포도", R.drawable.food4_21, "과일", "food4_21", 7));
            data.add(new FoodItem("한라봉", R.drawable.food4_22, "과일", "food4_22", 14));

            data.add(new FoodItem("냉면사리", R.drawable.food5_1, "면", "food5_1", 7));
            data.add(new FoodItem("당면", R.drawable.food5_2, "면", "food5_2", 180));
            data.add(new FoodItem("라면", R.drawable.food5_3, "면", "food5_3", 180));
            data.add(new FoodItem("메밀면", R.drawable.food5_4, "면", "food5_4", 5));
            data.add(new FoodItem("비빔면", R.drawable.food5_5, "면", "food5_5", 180));
            data.add(new FoodItem("소면", R.drawable.food5_6, "면", "food5_6", 180));
            data.add(new FoodItem("스파게티면", R.drawable.food5_7, "면", "food5_7", 180));
            data.add(new FoodItem("쌀국수면", R.drawable.food5_8, "면", "food5_8", 120));
            data.add(new FoodItem("우동면", R.drawable.food5_9, "면", "food5_9", 7));
            data.add(new FoodItem("짜장라면", R.drawable.food5_10, "면", "food5_10", 180));
            data.add(new FoodItem("쫄면사리", R.drawable.food5_11, "면", "food5_11", 5));
            data.add(new FoodItem("칼국수면", R.drawable.food5_12, "면", "food5_12", 7));
            data.add(new FoodItem("파스타면", R.drawable.food5_13, "면", "food5_13", 180));

            data.add(new FoodItem("가래떡", R.drawable.food6_1, "빵/떡", "food6_1", 3));
            data.add(new FoodItem("떡", R.drawable.food6_2, "빵/떡", "food6_2", 3));
            data.add(new FoodItem("떡국떡", R.drawable.food6_3, "빵/떡", "food6_3", 5));
            data.add(new FoodItem("떡볶이떡", R.drawable.food6_4, "빵/떡", "food6_4", 5));
            data.add(new FoodItem("또띠아", R.drawable.food6_5, "빵/떡", "food6_5", 7));
            data.add(new FoodItem("바게트", R.drawable.food6_6, "빵/떡", "food6_6", 2));
            data.add(new FoodItem("베이글", R.drawable.food6_7, "빵/떡", "food6_7", 5));
            data.add(new FoodItem("빵", R.drawable.food6_8, "빵/떡", "food6_8", 5));
            data.add(new FoodItem("식빵", R.drawable.food6_9, "빵/떡", "food6_9", 5));
            data.add(new FoodItem("즉석밥", R.drawable.food6_10, "빵/떡", "food6_10", 180));
            data.add(new FoodItem("케이크", R.drawable.food6_11, "빵/떡", "food6_11", 3));
            data.add(new FoodItem("피자", R.drawable.food6_12, "빵/떡", "food6_12", 3));

            data.add(new FoodItem("감귤주스", R.drawable.food7_1, "음료/주류", "food7_1", 10));
            data.add(new FoodItem("망고주스", R.drawable.food7_2, "음료/주류", "food7_2", 10));
            data.add(new FoodItem("맥주", R.drawable.food7_3, "음료/주류", "food7_3", 180));
            data.add(new FoodItem("사이다", R.drawable.food7_4, "음료/주류", "food7_4", 60));
            data.add(new FoodItem("생수", R.drawable.food7_5, "음료/주류", "food7_5", 1000));
            data.add(new FoodItem("소주", R.drawable.food7_6, "음료/주류", "food7_6", 360));
            data.add(new FoodItem("오렌지주스", R.drawable.food7_7, "음료/주류", "food7_7", 10));
            data.add(new FoodItem("제로콜라", R.drawable.food7_8, "음료/주류", "food7_8", 300));
            data.add(new FoodItem("콜라", R.drawable.food7_9, "음료/주류", "food7_9", 300));
            data.add(new FoodItem("탄산수", R.drawable.food7_10, "음료/주류", "food7_10", 300));
            data.add(new FoodItem("포도주스", R.drawable.food7_11, "음료/주류", "food7_11", 10));
            data.add(new FoodItem("환타", R.drawable.food7_12, "음료/주류", "food7_12", 300));

            data.add(new FoodItem("가지", R.drawable.food8_1, "채소", "food8_1", 7));
            data.add(new FoodItem("감자", R.drawable.food8_2, "채소", "food8_2", 30));
            data.add(new FoodItem("고구마", R.drawable.food8_3, "채소", "food8_3", 20));
            data.add(new FoodItem("고수", R.drawable.food8_4, "채소", "food8_4", 7));
            data.add(new FoodItem("고추", R.drawable.food8_5, "채소", "food8_5", 14));
            data.add(new FoodItem("깻잎", R.drawable.food8_6, "채소", "food8_6", 5));
            data.add(new FoodItem("꽈리고추", R.drawable.food8_7, "채소", "food8_7", 7));
            data.add(new FoodItem("냉이", R.drawable.food8_8, "채소", "food8_8", 5));
            data.add(new FoodItem("단호박", R.drawable.food8_9, "채소", "food8_9", 30));
            data.add(new FoodItem("달래", R.drawable.food8_10, "채소", "food8_10", 7));
            data.add(new FoodItem("당근", R.drawable.food8_11, "채소", "food8_11", 21));
            data.add(new FoodItem("대파", R.drawable.food8_12, "채소", "food8_12", 7));
            data.add(new FoodItem("두릅", R.drawable.food8_13, "채소", "food8_13", 5));
            data.add(new FoodItem("딜", R.drawable.food8_14, "채소", "food8_14", 5));
            data.add(new FoodItem("로즈마리", R.drawable.food8_15, "채소", "food8_15", 10));
            data.add(new FoodItem("마늘", R.drawable.food8_16, "채소", "food8_16", 30));
            data.add(new FoodItem("마늘쫑", R.drawable.food8_17, "채소", "food8_17", 7));
            data.add(new FoodItem("무", R.drawable.food8_18, "채소", "food8_18", 30));
            data.add(new FoodItem("미나리", R.drawable.food8_19, "채소", "food8_19", 5));
            data.add(new FoodItem("바질", R.drawable.food8_20, "채소", "food8_20",5));
            data.add(new FoodItem("방울토마토", R.drawable.food8_21, "채소", "food8_21", 10));
            data.add(new FoodItem("배추", R.drawable.food8_22, "채소", "food8_22", 14));
            data.add(new FoodItem("버섯", R.drawable.food8_23, "채소", "food8_23",5));
            data.add(new FoodItem("봄동", R.drawable.food8_24, "채소", "food8_24", 7));
            data.add(new FoodItem("부추", R.drawable.food8_25, "채소", "food8_25", 5));
            data.add(new FoodItem("브로콜리", R.drawable.food8_26, "채소", "food8_26", 7));
            data.add(new FoodItem("상추", R.drawable.food8_27, "채소", "food8_27", 5));
            data.add(new FoodItem("샐러드", R.drawable.food8_28, "채소", "food8_28", 3));
            data.add(new FoodItem("샐러리", R.drawable.food8_29, "채소", "food8_29", 14));
            data.add(new FoodItem("생강", R.drawable.food8_30, "채소", "food8_30", 30));
            data.add(new FoodItem("숙주", R.drawable.food8_31, "채소", "food8_31", 3));
            data.add(new FoodItem("시금치", R.drawable.food8_32, "채소", "food8_32", 5));
            data.add(new FoodItem("쑥", R.drawable.food8_33, "채소", "food8_33", 5));
            data.add(new FoodItem("쑥갓", R.drawable.food8_34, "채소", "food8_34", 5));
            data.add(new FoodItem("아보카도", R.drawable.food8_35, "채소", "food8_35", 5));
            data.add(new FoodItem("아스파라거스", R.drawable.food8_36, "채소", "food8_36", 7));
            data.add(new FoodItem("애플민트", R.drawable.food8_37, "채소", "food8_37",5));
            data.add(new FoodItem("애호박", R.drawable.food8_38, "채소", "food8_38", 10));
            data.add(new FoodItem("양배추", R.drawable.food8_39, "채소", "food8_39", 21));
            data.add(new FoodItem("양상추", R.drawable.food8_40, "채소", "food8_40", 7));
            data.add(new FoodItem("양송이버섯", R.drawable.food8_41, "채소", "food8_41", 5));
            data.add(new FoodItem("양파", R.drawable.food8_42, "채소", "food8_42", 60));
            data.add(new FoodItem("연근", R.drawable.food8_43, "채소", "food8_43", 10));
            data.add(new FoodItem("열무", R.drawable.food8_44, "채소", "food8_44", 7));
            data.add(new FoodItem("오이", R.drawable.food8_45, "채소", "food8_45", 7));
            data.add(new FoodItem("올리브", R.drawable.food8_46, "채소", "food8_46",30));
            data.add(new FoodItem("우엉", R.drawable.food8_47, "채소", "food8_47", 14));
            data.add(new FoodItem("쪽파", R.drawable.food8_48, "채소", "food8_48", 7));
            data.add(new FoodItem("청경채", R.drawable.food8_49, "채소", "food8_49", 5));
            data.add(new FoodItem("청양고추", R.drawable.food8_50, "채소", "food8_50", 10));
            data.add(new FoodItem("취나물", R.drawable.food8_51, "채소", "food8_51", 5));
            data.add(new FoodItem("콩나물", R.drawable.food8_52, "채소", "food8_52", 5));
            data.add(new FoodItem("타임", R.drawable.food8_53, "채소", "food8_53", 10));
            data.add(new FoodItem("토마토", R.drawable.food8_54, "채소", "food8_54", 7));
            data.add(new FoodItem("파프리카", R.drawable.food8_55, "채소", "food8_55", 14));
            data.add(new FoodItem("팽이버섯", R.drawable.food8_56, "채소", "food8_56", 5));
            data.add(new FoodItem("표고버섯", R.drawable.food8_57, "채소", "food8_57", 5));
            data.add(new FoodItem("피망", R.drawable.food8_58, "채소", "food8_58", 14));
            data.add(new FoodItem("호박", R.drawable.food8_59, "채소", "food8_59", 10));
            data.add(new FoodItem("홍고추", R.drawable.food8_60, "채소", "food8_60", 10));

            data.add(new FoodItem("검은콩", R.drawable.food9_1, "콩/견과류", "food9_1", 180));
            data.add(new FoodItem("두부", R.drawable.food9_2, "콩/견과류", "food9_2", 23));
            data.add(new FoodItem("땅콩", R.drawable.food9_3, "콩/견과류", "food9_3", 180));
            data.add(new FoodItem("밤", R.drawable.food9_4, "콩/견과류", "food9_4", 30));
            data.add(new FoodItem("순두부", R.drawable.food9_5, "콩/견과류", "food9_5", 20));
            data.add(new FoodItem("시리얼", R.drawable.food9_6, "콩/견과류", "food9_6", 180));
            data.add(new FoodItem("아몬드", R.drawable.food9_7, "콩/견과류", "food9_7", 270));
            data.add(new FoodItem("연두부", R.drawable.food9_8, "콩/견과류", "food9_8", 20));
            data.add(new FoodItem("오트밀", R.drawable.food9_9, "콩/견과류", "food9_9", 180));
            data.add(new FoodItem("완두콩", R.drawable.food9_10, "콩/견과류", "food9_10", 7));
            data.add(new FoodItem("유부", R.drawable.food9_11, "콩/견과류", "food9_11", 10));
            data.add(new FoodItem("잣", R.drawable.food9_12, "콩/견과류", "food9_12", 120));
            data.add(new FoodItem("코코넛", R.drawable.food9_13, "콩/견과류", "food9_13", 30));
            data.add(new FoodItem("콩", R.drawable.food9_14, "콩/견과류", "food9_14", 180));
            data.add(new FoodItem("피스타치오", R.drawable.food9_15, "콩/견과류", "food9_15", 180));
            data.add(new FoodItem("헤이즐넛", R.drawable.food9_16, "콩/견과류", "food9_16", 180));
            data.add(new FoodItem("호두", R.drawable.food9_17, "콩/견과류", "food9_17", 120));

            data.add(new FoodItem("갈치", R.drawable.food10_1, "해산물", "food10_1", 2));
            data.add(new FoodItem("고등어", R.drawable.food10_2, "해산물", "food10_2", 2));
            data.add(new FoodItem("골뱅이", R.drawable.food10_3, "해산물", "food10_3", 3));
            data.add(new FoodItem("굴", R.drawable.food10_4, "해산물", "food10_4", 2));
            data.add(new FoodItem("굴비", R.drawable.food10_5, "해산물", "food10_5", 2));
            data.add(new FoodItem("김", R.drawable.food10_6, "해산물", "food10_6", 180));
            data.add(new FoodItem("꼬막", R.drawable.food10_7, "해산물", "food10_7", 5));
            data.add(new FoodItem("꽁치", R.drawable.food10_8, "해산물", "food10_8", 2));
            data.add(new FoodItem("꽃게", R.drawable.food10_9, "해산물", "food10_9", 2));
            data.add(new FoodItem("낙지", R.drawable.food10_10, "해산물", "food10_10", 2));
            data.add(new FoodItem("도미", R.drawable.food10_11, "해산물", "food10_11", 2));
            data.add(new FoodItem("동태", R.drawable.food10_12, "해산물", "food10_12", 2));
            data.add(new FoodItem("멍게", R.drawable.food10_13, "해산물", "food10_13", 2));
            data.add(new FoodItem("멸치", R.drawable.food10_14, "해산물", "food10_14", 180));
            data.add(new FoodItem("명란젓", R.drawable.food10_15, "해산물", "food10_15", 7));
            data.add(new FoodItem("명태", R.drawable.food10_16, "해산물", "food10_16", 10));
            data.add(new FoodItem("문어", R.drawable.food10_17, "해산물", "food10_17", 3));
            data.add(new FoodItem("미역", R.drawable.food10_18, "해산물", "food10_18", 3));
            data.add(new FoodItem("바지락", R.drawable.food10_19, "해산물", "food10_19", 4));
            data.add(new FoodItem("삼치", R.drawable.food10_20, "해산물", "food10_20", 2));
            data.add(new FoodItem("새우", R.drawable.food10_21, "해산물", "food10_21", 3));
            data.add(new FoodItem("소라", R.drawable.food10_22, "해산물", "food10_22", 4));
            data.add(new FoodItem("아귀", R.drawable.food10_23, "해산물", "food10_23", 2));
            data.add(new FoodItem("어묵", R.drawable.food10_24, "해산물", "food10_24", 40));
            data.add(new FoodItem("연어", R.drawable.food10_25, "해산물", "food10_25", 2));
            data.add(new FoodItem("오징어", R.drawable.food10_26, "해산물", "food10_26", 2));
            data.add(new FoodItem("오징어젓갈", R.drawable.food10_27, "해산물", "food10_27", 90));
            data.add(new FoodItem("장어", R.drawable.food10_28, "해산물", "food10_28", 2 ));
            data.add(new FoodItem("전복", R.drawable.food10_29, "해산물", "food10_29", 3));
            data.add(new FoodItem("전어", R.drawable.food10_30, "해산물", "food10_30", 2));
            data.add(new FoodItem("조개", R.drawable.food10_31, "해산물", "food10_31", 4));
            data.add(new FoodItem("조기", R.drawable.food10_32, "해산물", "food10_32", 2));
            data.add(new FoodItem("진미오징어", R.drawable.food10_33, "해산물", "food10_33", 180));
            data.add(new FoodItem("쭈꾸미", R.drawable.food10_34, "해산물", "food10_34", 2));
            data.add(new FoodItem("칵테일새우", R.drawable.food10_35, "해산물", "food10_35", 500));
            data.add(new FoodItem("홍합", R.drawable.food10_36, "해산물", "food10_36", 4));

            data.add(new FoodItem("겨자", R.drawable.food11_1, "조미료/양념", "food11_1", 180));
            data.add(new FoodItem("고추냉이", R.drawable.food11_2, "조미료/양념", "food11_2", 360));
            data.add(new FoodItem("고추장", R.drawable.food11_3, "조미료/양념", "food11_3", 180));
            data.add(new FoodItem("고춧가루", R.drawable.food11_4, "조미료/양념", "food11_4", 360));
            data.add(new FoodItem("국간장", R.drawable.food11_5, "조미료/양념", "food11_5", 700));
            data.add(new FoodItem("굴소스", R.drawable.food11_6, "조미료/양념", "food11_6", 500));
            data.add(new FoodItem("까나리액젓", R.drawable.food11_7, "조미료/양념", "food11_7", 500));
            data.add(new FoodItem("꿀", R.drawable.food11_8, "조미료/양념", "food11_8", 700));
            data.add(new FoodItem("녹차가루", R.drawable.food11_9, "조미료/양념", "food11_9", 700));
            data.add(new FoodItem("다시다", R.drawable.food11_10, "조미료/양념", "food11_10", 360));
            data.add(new FoodItem("다시마", R.drawable.food11_11, "조미료/양념", "food11_11", 700));
            data.add(new FoodItem("다진마늘", R.drawable.food11_12, "조미료/양념", "food11_12", 14));
            data.add(new FoodItem("돈까스소스", R.drawable.food11_13, "조미료/양념", "food11_13", 180));
            data.add(new FoodItem("된장", R.drawable.food11_14, "조미료/양념", "food11_14", 360));
            data.add(new FoodItem("들기름", R.drawable.food11_15, "조미료/양념", "food11_15", 330));
            data.add(new FoodItem("레몬즙", R.drawable.food11_16, "조미료/양념", "food11_16", 14));
            data.add(new FoodItem("마라소스", R.drawable.food11_17, "조미료/양념", "food11_17", 270));
            data.add(new FoodItem("마요네즈", R.drawable.food11_18, "조미료/양념", "food11_18", 330));
            data.add(new FoodItem("맛술", R.drawable.food11_19, "조미료/양념", "food11_19", 270));
            data.add(new FoodItem("매실청", R.drawable.food11_20, "조미료/양념", "food11_20", 270));
            data.add(new FoodItem("머스타드", R.drawable.food11_21, "조미료/양념", "food11_21", 360));
            data.add(new FoodItem("메이플시럽", R.drawable.food11_22, "조미료/양념", "food11_22", 270));
            data.add(new FoodItem("멸치액젓", R.drawable.food11_23, "조미료/양념", "food11_23", 500));
            data.add(new FoodItem("물엿", R.drawable.food11_24, "조미료/양념", "food11_24", 90));
            data.add(new FoodItem("미소된장", R.drawable.food11_25, "조미료/양념", "food11_25", 270));
            data.add(new FoodItem("바질페스토", R.drawable.food11_26, "조미료/양념", "food11_26", 14));
            data.add(new FoodItem("살사소스", R.drawable.food11_27, "조미료/양념", "food11_27", 7));
            data.add(new FoodItem("새우젓", R.drawable.food11_28, "조미료/양념", "food11_28", 90));
            data.add(new FoodItem("설탕", R.drawable.food11_29, "조미료/양념", "food11_29", 1000));
            data.add(new FoodItem("소금", R.drawable.food11_30, "조미료/양념", "food11_30", 1000));
            data.add(new FoodItem("스리라차소스", R.drawable.food11_31, "조미료/양념", "food11_31", 60));
            data.add(new FoodItem("스테비아", R.drawable.food11_32, "조미료/양념", "food11_32", 1000));
            data.add(new FoodItem("스테이크소스", R.drawable.food11_33, "조미료/양념", "food11_33", 180));
            data.add(new FoodItem("식용유", R.drawable.food11_34, "조미료/양념", "food11_34", 180));
            data.add(new FoodItem("식초", R.drawable.food11_35, "조미료/양념", "food11_35", 1000));
            data.add(new FoodItem("쌈장", R.drawable.food11_36, "조미료/양념", "food11_36", 500));
            data.add(new FoodItem("알룰로스", R.drawable.food11_37, "조미료/양념", "food11_37", 500));
            data.add(new FoodItem("양조간장", R.drawable.food11_38, "조미료/양념", "food11_38", 500));
            data.add(new FoodItem("연겨자", R.drawable.food11_39, "조미료/양념", "food11_39", 500));
            data.add(new FoodItem("연두", R.drawable.food11_40, "조미료/양념", "food11_40", 180));
            data.add(new FoodItem("올리고당", R.drawable.food11_41, "조미료/양념", "food11_41", 500));
            data.add(new FoodItem("올리브유", R.drawable.food11_42, "조미료/양념", "food11_42", 500));
            data.add(new FoodItem("우스타소스", R.drawable.food11_43, "조미료/양념", "food11_43", 500));
            data.add(new FoodItem("조청", R.drawable.food11_44, "조미료/양념", "food11_44", 270));
            data.add(new FoodItem("진간장", R.drawable.food11_45, "조미료/양념", "food11_45", 500));
            data.add(new FoodItem("짜장분말", R.drawable.food11_46, "조미료/양념", "food11_46", 400));
            data.add(new FoodItem("참기름", R.drawable.food11_47, "조미료/양념", "food11_47", 480));
            data.add(new FoodItem("참치액젓", R.drawable.food11_48, "조미료/양념", "food11_48", 500));
            data.add(new FoodItem("청국장", R.drawable.food11_49, "조미료/양념", "food11_49", 500));
            data.add(new FoodItem("청주", R.drawable.food11_50, "조미료/양념", "food11_50", 180));
            data.add(new FoodItem("초고추장", R.drawable.food11_51, "조미료/양념", "food11_51", 300));
            data.add(new FoodItem("칠리소스", R.drawable.food11_52, "조미료/양념", "food11_52", 180));
            data.add(new FoodItem("카라멜시럽", R.drawable.food11_53, "조미료/양념", "food11_53", 500));
            data.add(new FoodItem("카레분말", R.drawable.food11_54, "조미료/양념", "food11_54", 500));
            data.add(new FoodItem("케찹", R.drawable.food11_55, "조미료/양념", "food11_55", 240));
            data.add(new FoodItem("타르타르소스", R.drawable.food11_56, "조미료/양념", "food11_56", 7));
            data.add(new FoodItem("통후추", R.drawable.food11_57, "조미료/양념", "food11_57", 500));
            data.add(new FoodItem("파슬리", R.drawable.food11_58, "조미료/양념", "food11_58", 1000));
            data.add(new FoodItem("페페로치노", R.drawable.food11_59, "조미료/양념", "food11_59", 1000));
            data.add(new FoodItem("핫소스", R.drawable.food11_60, "조미료/양념", "food11_60", 270));
            data.add(new FoodItem("홀그레인머스타드", R.drawable.food11_61, "조미료/양념", "food11_61",180));
            data.add(new FoodItem("후추", R.drawable.food11_62, "조미료/양념", "food11_62", 500));

            data.add(new FoodItem("김치", R.drawable.food12_1, "기타", "food12_1", 45));
            data.add(new FoodItem("깍두기", R.drawable.food12_2, "기타", "food12_2", 45));
            data.add(new FoodItem("묵은지", R.drawable.food12_3, "기타", "food12_3", 1000));
            data.add(new FoodItem("백김치", R.drawable.food12_4, "기타", "food12_4", 45));
            data.add(new FoodItem("사과잼", R.drawable.food12_5, "기타", "food12_5", 90));
            data.add(new FoodItem("열무김치", R.drawable.food12_6, "기타", "food12_6", 80));
            data.add(new FoodItem("총각김치", R.drawable.food12_7, "기타", "food12_7", 45));
            data.add(new FoodItem("케이퍼", R.drawable.food12_8, "기타", "food12_8", 180));
            data.add(new FoodItem("파김치", R.drawable.food12_9, "기타", "food12_9", 30));
            data.add(new FoodItem("할라피뇨", R.drawable.food12_10, "기타", "food12_10", 14));
        }
        return data;
        // 게터 메소드 호출 시 바로 리스트 반환함
    }

}
